name: NaturalCore
version: 1.1.0
main: id.naturalsmp.naturalcore.NaturalCore
api-version: 1.20
author: NaturalSMP
description: Core plugin untuk NaturalSMP Server

depend: [Vault]
softdepend: [Citizens, DecentHolograms]

# ==========================================
# DAFTAR COMMANDS
# ==========================================
commands:
  # --- CORE ---
  nacore:
    description: Command utama untuk admin (Reload/Version)
    aliases: [nc, naturalcore]
    permission: naturalsmp.admin
    usage: /nacore <help|reload|version>

  # --- ADMIN MODULE ---
  kickall:
    description: Kick seluruh player di server
    permission: naturalcs.kickall
    usage: /kickall confirm <alasan>

  restartalert:
    description: Memulai hitung mundur restart server
    aliases: [ra]
    permission: naturalcs.restartalert
    usage: /restartalert confirm

  bc:
    description: Broadcast pesan ke seluruh server
    aliases: [broadcast, siar]
    permission: naturalcs.broadcast
    usage: /bc <pesan>

  # --- WARP MODULE ---
  warp:
    description: Teleport ke warp atau buka menu warp
    usage: /warp [nama]

  warps:
    description: Buka menu warp GUI
    usage: /warps [edit]

  setwarp:
    description: Membuat warp baru di lokasi saat ini
    permission: naturalsmp.admin
    usage: /setwarp <nama>

  delwarp:
    description: Menghapus warp
    permission: naturalsmp.admin
    usage: /delwarp <nama>

  setwarpicon:
    description: Set icon warp ke item di tangan
    permission: naturalsmp.admin
    usage: /setwarpicon <nama>

  # --- TRADER MODULE ---
  wanderingtrader:
    description: Mengelola Wandering Trader
    aliases: [wt, trader]
    permission: naturalsmp.admin
    usage: /wanderingtrader <spawn|despawn|setloc|setinterval|next>

  givecurrency:
    description: Memberikan Quest Paper ke player
    permission: naturalsmp.admin
    usage: /givecurrency <player> <amount>

  tradeeditor:
    description: Buka GUI trade editor
    permission: naturalsmp.admin
    usage: /tradeeditor

# ==========================================
# DAFTAR PERMISSIONS
# ==========================================
permissions:
  naturalsmp.admin:
    description: Izin full akses NaturalCore
    default: op

  naturalcs.kickall:
    description: Izin kick semua player
    default: op

  naturalcs.restartalert:
    description: Izin alert restart
    default: op

  naturalcs.broadcast:
    description: Izin broadcast
    default: op