name: NaturalCore
version: 1.5
main: id.naturalsmp.naturalcore.NaturalCore
api-version: 1.21
author: NaturalSMP
description: Core plugin untuk NaturalSMP Server
depend: [Vault, DecentHolograms]
softdepend: [PlaceholderAPI, CoinsEngine]

# ==========================================
# DAFTAR COMMANDS
# ==========================================
commands:
  # --- CORE ---
  nacore:
    description: Main command plugin
    permission: naturalsmp.admin
  kickall:
    description: Kick seluruh player
    permission: naturalcs.kickall
  restartalert:
    description: Alert restart
    aliases: [ra]
    permission: naturalcs.restartalert
  bc:
    description: Broadcast
    aliases: [broadcast]
    permission: naturalcs.broadcast
  tp:
    description: Teleport admin
    permission: naturalsmp.tp
  tphere:
    description: Tarik player
    permission: naturalsmp.tphere

  endersee:
    description: Intip enderchest player lain
    aliases: [ecsee]
    permission: naturalsmp.endersee

  # --- MESSAGING ---
  msg:
    description: Kirim pesan pribadi
    aliases: [tell, w, whisper]
  reply:
    description: Balas pesan terakhir
    aliases: [r]

  # --- UTILITIES (WORLD) ---
  day:
    description: Ubah waktu ke siang
    permission: naturalsmp.time
  night:
    description: Ubah waktu ke malam
    permission: naturalsmp.time
  sun:
    description: Ubah cuaca cerah
    permission: naturalsmp.time
  rain:
    description: Ubah cuaca hujan
    permission: naturalsmp.time

  # --- PERKS ---
  hat:
    description: Pakai item di kepala
    permission: naturalsmp.hat
  repair:
    description: Perbaiki item
    aliases: [fix]
    permission: naturalsmp.repair
  nick:
    description: Ganti nickname
    aliases: [nickname]
    permission: naturalsmp.nick

  # --- ECONOMY ---
  givebal:
    description: Give balance
    permission: naturalcs.givebalance
  setbal:
    description: Set saldo
    permission: naturalsmp.economy.admin
  takebal:
    description: Tarik saldo
    permission: naturalsmp.economy.admin
  baltop:
    description: Top balance
  bal:
    description: Cek saldo
    aliases: [balance, money]
  pay:
    description: Kirim uang

  # --- ESSENTIALS ---
  gamemode:
    description: Gamemode
    aliases: [gm]
    permission: naturalsmp.gamemode
  gmc:
    description: Creative
    permission: naturalsmp.gamemode
  gms:
    description: Survival
    permission: naturalsmp.gamemode
  gma:
    description: Adventure
    permission: naturalsmp.gamemode
  gmsp:
    description: Spectator
    permission: naturalsmp.gamemode

  fly:
    description: Terbang
    permission: naturalsmp.fly
  heal:
    description: Heal
    permission: naturalsmp.heal
  feed:
    description: Feed
    permission: naturalsmp.feed
  trash:
    description: Sampah
  craft:
    description: Crafting
    aliases: [wb]
    permission: naturalsmp.craft
  anvil:
    description: Buka virtual anvil
    aliases: [ av ]
    permission: naturalsmp.anvil
  invsee:
    description: Cek tas
    permission: naturalsmp.invsee
  enderchest:
    description: Buka enderchest sendiri
    aliases: [ec]
    permission: naturalsmp.enderchest

  # --- MODERATION ---
  god:
    description: God mode
    permission: naturalsmp.god
  vanish:
    description: Vanish
    aliases: [v]
    permission: naturalsmp.vanish
  whois:
    description: Info player
    permission: naturalsmp.whois

  # --- WARP ---
  warp:
    description: Ke warp
  warps:
    description: Menu warp
  setwarp:
    description: Set warp
    permission: naturalsmp.admin
  delwarp:
    description: Hapus warp
    permission: naturalsmp.admin
  setwarpicon:
    description: Icon warp
    permission: naturalsmp.admin

  # --- TRADER ---
  traderadmin:
    description: Admin trader configuration
    usage: /traderadmin <create|remove|list|reload>
    permission: naturalsmp.admin

  # --- SPAWN ---
  spawn:
    description: Ke spawn
    permission: naturalsmp.spawn
  setspawn:
    description: Set spawn
    permission: naturalsmp.admin

  # --- HOME ---
  sethome:
    description: Set home
    permission: naturalsmp.home.use
  delhome:
    description: Hapus home
    permission: naturalsmp.home.use
  home:
    description: Ke home
    permission: naturalsmp.home.use
  homes:
    description: List home
    permission: naturalsmp.home.use

  # --- FUN & RTP ---
  gg:
    description: GG
  noob:
    description: Noob
  resource:
    description: RTP Resource
    aliases: [rsc]
    permission: naturalsmp.resource
  survival:
    description: RTP Survival
    aliases: [rtp]

  # --- TPA ---
  tpa:
    description: TPA Request
  tpahere:
    description: TPA Here
  tpaccept:
    description: Accept
  tpdeny:
    description: Deny

  # --- EMOJI ---
  emoji:
    description: Lihat daftar emoji yang tersedia
    aliases: [emojis, emoticon]
    permission: naturalsmp.emoji.use

permissions:
  naturalsmp.admin:
    default: op
  naturalcs.kickall:
    default: op
  naturalcs.restartalert:
    default: op
  naturalcs.broadcast:
    default: op
  naturalsmp.home.limit.*:
    description: Izin untuk semua jenis limit home
    children:
      naturalsmp.home.limit.default: true
      naturalsmp.home.limit.unlimited: true
  naturalsmp.home.limit.unlimited:
    description: Izin untuk membuat home tanpa batas
    default: op