name: NaturalCore
version: 1.0.0
main: id.naturalsmp.naturalcore.NaturalCore
api-version: 1.20
author: NaturalSMP
description: Core plugin untuk NaturalSMP Server

depend: [Vault]
softdepend: [Citizens, DecentHolograms]

# ==========================================
# DAFTAR COMMANDS
# ==========================================
commands:
  # --- CORE (Jantung Plugin) ---
  nacore:
    description: Command utama untuk admin (Reload/Version)
    aliases: [nc, naturalcore]
    permission: naturalsmp.admin
    usage: /nacore <help|reload|version>

  # --- ADMIN MODULE (Yang sudah kita buat) ---
  kickall:
    description: Kick seluruh player di server
    permission: naturalcs.kickall
    usage: /kickall confirm <alasan>

  restartalert:
    description: Memulai hitung mundur restart server
    aliases: [ra]
    permission: naturalcs.restartalert
    usage: /restartalert confirm

  bc:
    description: Broadcast pesan ke seluruh server
    aliases: [broadcast, siar]
    permission: naturalcs.broadcast
    usage: /bc <pesan>

  # --- ECONOMY MODULE (Next Project) ---
  givebal:
    description: Memberikan uang ke player (NaturalCoin)
    permission: naturalcs.givebalance
    usage: /givebal <player> <jumlah>

  # --- ALTAR QUEST MODULE (Future) ---
  altarwand:
    description: Mengambil wand untuk set lokasi altar
    permission: naturalsmp.admin

  altarstart:
    description: Memulai event donasi altar
    permission: naturalsmp.admin
    usage: /altarstart <jumlah1> [jumlah2] [jumlah3]

  altarsetworld:
    description: Mengatur world tujuan dungeon
    permission: naturalsmp.admin

  altarsetwarp:
    description: Mengatur titik spawn altar (sebelum dungeon buka)
    permission: naturalsmp.admin

  altarsettrigger:
    description: Mengatur blok donasi & lokasi hologram
    permission: naturalsmp.admin

  altardelete:
    description: Reset progress altar & hapus hologram
    permission: naturalsmp.admin

  dungeon:
    description: Teleport ke dungeon (Via Altar)
    aliases: [warp]

  # --- REFORGE MODULE (Future) ---
  reforgeadmin:
    description: Mengambil batu reforge (Admin)
    permission: op
    usage: /reforgeadmin <tipe> <stat> <chance>

  # --- TRADER MODULE (Future) ---
  wanderingtrader:
    description: Membuka menu trader real-time
    aliases: [wt, trader]

  resettrader:
    description: Reset stok trader
    permission: op

  setharga:
    description: Set harga trader manual
    permission: op

# ==========================================
# DAFTAR PERMISSIONS (Opsional - Biar rapi di LuckPerms)
# ==========================================
permissions:
  naturalsmp.admin:
    description: Izin full akses NaturalCore
    default: op

  naturalcs.kickall:
    description: Izin kick semua player
    default: op

  naturalcs.restartalert:
    description: Izin alert restart
    default: op

  naturalcs.broadcast:
    description: Izin broadcast
    default: op